### ISSUE TITLE
Fix broken mock reporting

### ISSUE THREAD

**Issue by vigoo** [zio/zio-mock#22]
Broke with the upgrade to ZIO 2.0.0-RC6, `MockReporterSpec` suite is now temporarily ignored to unblock migration of other projects.

**Comment by bilal-fazlani** [comment]
👀 
Using zio-mock is very difficult without reporting

**Comment by soujiro32167** [comment]
May be the cause of https://github.com/zio/zio-mock/issues/35

**Comment by regiskuckaertz** [comment]
Fixed in #51
