### ISSUE TITLE
UnsatisfiedExpectationsException: null

### ISSUE THREAD

**Issue by soujiro32167** [zio/zio-mock#35]
When running mocks with ZIO 2.0.2 and zio-mock 1.0.0-RC9, I get the following exception:
```
Exception in thread "zio-fiber-49" zio.mock.internal.MockException$UnsatisfiedExpectationsException: null
    	at zio.mock.internal.MockState$.$anonfun$checkUnmetExpectations$3(MockState.scala:41)
```

To reproduce:
```scala
import zio._
import zio.mock.{Expectation, Mock}
import zio.stream.ZStream
import zio.test._
import zio.test.Assertion._

object reproduce extends ZIOSpecDefault {
  trait Foo {
    def createDocument(document: ZStream[Any, Throwable, Byte]): Task[Unit]
  }

  object FooMock extends Mock[Foo] {
    object CreateDocument extends Effect[ZStream[Any, Throwable, Byte], Throwable, Unit]

    val compose: URLayer[mock.Proxy, Foo] = ZLayer.fromFunction { (proxy: mock.Proxy) =>
      new Foo {
        override def createDocument(document: ZStream[Any, Throwable, Byte]): Task[Unit] =
          proxy(CreateDocument, document)
      }
    }
  }

  def spec = suite("mocks")(
    test("fail?") {
      for {
        _ <- ZIO.serviceWithZIO[Foo](_.createDocument(ZStream.empty))
      } yield assertCompletes
    }.provide(
      FooMock.CreateDocument(equalTo(ZStream.empty), Expectation.unit)
    )
  )
}
```
Scastie: https://scastie.scala-lang.org/soujiro32167/p6PBZRuGQwa7vXrmToKt8w/7

**Comment by soujiro32167** [comment]
Actually, this is not even about streams. This error happens when ANY expectation is unmet 😱

**Comment by lachezar** [comment]
I just encountered this issue 😵‍💫

**Comment by regiskuckaertz** [comment]
Hey - I just rewrote a whole app to ZIO 2 and that was the hardest part. There is a way to get the reporting: use `sut.exit` to get details about the exception. It is far from ideal, but it works.

I have not looked into the code, but if given proper indications of where to look, I am happy to try and submit a fix for this.

**Comment by vigoo** [comment]
Hi @regiskuckaertz! 

This is broken because of https://github.com/zio/zio-mock/issues/22 - it was a compromise as I did not have time to look into this but wanted to have a somewhat working version so other libraries like zio-aws can move forward in the migration process. 

If you could help fixing it it would be really appreciated!

Some info:
- There were tests verifying that the expectations are properly reported in `MockReporterSpec` and now they are `ignore`d. So I would start by reenabling those tests.
- It broke in RC6 when zio-test switched to its new streaming reporting interface. I think this is the primary related commit: https://github.com/zio/zio/pull/6405. I don't remember though why (or whether I ever knew why ;) I'm not really familiar with this project either). 
- I suspect the problem is in the `MockReporter` object, not properly catching and/or rendering these exceptions

**Comment by regiskuckaertz** [comment]
@vigoo ok thanks for that! I'm going to go through each error at a time and the first easy one is this expectation:
```
✖ Expected a call to zio.mock.MockConsole.Print(equalTo(foo)), but zio.mock.MockConsole.PrintLine was invoked instead.  (HINT: Remember order is important when considering mock invocations.)
```
is not met because the assertion is rendered like so:
```scala
private def renderAssertion(ass: Assertion[_]): String = bold(magenta(ass.toString()))
```

which uses the stock Java `toString`. Is there an assertion renderer provided by zio-test?

**Comment by regiskuckaertz** [comment]
@swoogles Hi 👋 Sorry to pull you in, just wondering if you could point me to the right way of rendering an assertion here. I found `ConsoleRenderer` and something that looks useful maybe (`renderRuntimeCause`) but the output is a `ExecutionResult` and it is not clear how to plug the mock-specific error messages into it, or how to turn it into a string. Also the `MockReporter` only handles `TestFailure.Runtime`, should it also process `TestFailure.Assertion`?

**Comment by swoogles** [comment]
Hey @regiskuckaertz , I'm on holiday this week but will take a look on Sunday or Monday!

**Comment by regiskuckaertz** [comment]
@swoogles happy thanksgiving!

**Comment by BalduinLandolt** [comment]
What is the state on this? Could I potentially contribute?

**Comment by dag2ww** [comment]
+1 to above - it's really painful now if you have to deal with failing more complex tests... Any chance to have a fix for this pushed forward?

**Comment by SirStoke** [comment]
Hey! I managed to update zio-mock into failing with something like this:

```    
- MockReporterSpec - Behavior - fail?
      Exception in thread "zio-fiber-471" zio.mock.internal.MockException$InvalidCallException: equalTo(zio.stream.ZStream@7bc5ab8a)
      	at zio.mock.internal.ProxyFactory$$anon$1.$anonfun$invoke$37(ProxyFactory.scala:374)
      	at zio.ZIO$.$anonfun$die$1(ZIO.scala:3095)
      	at zio.ZIO$.$anonfun$failCause$1(ZIO.scala:3166)
      	at zio.mock.MockReporterSpec.behaviorSuite(MockReporterSpec.scala:156)
      	at zio.mock.MockReporterSpec.behaviorSuite(MockReporterSpec.scala:153)
      	at zio.mock.MockReporterSpec.behaviorSuite(MockReporterSpec.scala:151)
```

Using the repro code in the original issue - would this be good enough to contribute? Or would you like to fix it into something better / more descriptive?

**Comment by dag2ww** [comment]
Hi, is there any chance to have a mocked method info as well - so in this case `CreateDocument`?

**Comment by SirStoke** [comment]
#45 should fix this, as long as tests implement the `MockReporter` aspect (`@@ MockReporter()`) or the spec extends `MockSpecDefault` (which does the former automatically)

**Comment by DGolubets** [comment]
Hi, any progress on this?

**Comment by mateuszbrzezinski** [comment]
I have similar error, using example from docs:

<img width="601" alt="image" src="https://github.com/zio/zio-mock/assets/1177739/a8a66927-aaf2-4f95-bb0e-df5afb446f8e">


and it fails with:
<img width="1300" alt="image" src="https://github.com/zio/zio-mock/assets/1177739/6efa4a1f-53a7-4fcd-a28c-5d361a6f8c3e">

Is there any solution for that?

**Comment by mateuszbrzezinski** [comment]
So it seems real Random is called, not the MockRandom

**Comment by regiskuckaertz** [comment]
Just tested with the latest snapshot and that doesn't seem to happen anymore. Any chance we could get a new release @adamgfraser  @vigoo ? 🙇‍♂️

**Comment by soujiro32167** [comment]
I've updated the scastie to latest ZIO and zio-mocks, but still getting the same behavior =[
https://scastie.scala-lang.org/soujiro32167/p6PBZRuGQwa7vXrmToKt8w/11

**Comment by SirStoke** [comment]
> I've updated the scastie to latest ZIO and zio-mocks, but still getting the same behavior =[ https://scastie.scala-lang.org/soujiro32167/p6PBZRuGQwa7vXrmToKt8w/11

As mentioned above, you have to extend `MockSpecDefault` instead of `ZIOSpecDefault`. Your example [works otherwise](https://scastie.scala-lang.org/xwLeShIRSiW0oYeuoJ9Qwg).

**Comment by soujiro32167** [comment]
Totally missed that! Thanks @SirStoke
