### ISSUE TITLE
Lost Documentation

### ISSUE THREAD

**Issue by AcordUch** [zio/zio-mock#50]
I don't know if I should write here on this issue, but the link to the documentation (https://zio.dev/ecosystem/officials/zio-mock) gives `Page Not Found`. So it looks like there is no docs for zio-mock right now

**Comment by vigoo** [comment]
@khajavi

**Comment by FWennerdahl** [comment]
For anyone else looking for the documentation until this is fixed, this seems to be the last version of it before it was removed from the main zio repo: https://github.com/zio/zio/blob/a7683b44ed7749bee339e23df1c7248101f393d1/docs/ecosystem/officials/zio-mock.md

**Comment by khajavi** [comment]
Yes, the docs are moved to zio-mock project. I'll check to see why the latest version of zio-mock docs is not up and running on zio.dev/zio-mock
